// Scripted beats, ages 13-21. The years where the three big talents — sport,
// business and music — start pulling in different directions.

export const TEEN = [
  // --------------------------------------------------------------- AGE 13
  {
    id: 'a13_saintchris', age: 13, scene: 'school_high',
    intro: 'St Christopher School, Letchworth. And a fourth house in thirteen years.',
    prompt: 'Saint Chris does things differently. First-name terms with staff, and a lot more rope.',
    options: [
      { id: 'rope', label: 'Take the rope and run with it',
        fx: { CRE: 10, NAU: 7, CHA: 7 }, xp: 140, flag: 'sc_freedom',
        result: 'You realise within a week that if you ask for things properly here, you get them. You start asking for a lot of things.' },
      { id: 'work', label: 'Actually knuckle down — this place rewards it',
        fx: { SMR: 11, COD: 5, HAP: 4 }, xp: 140, flag: 'sc_scholar',
        result: 'For the first time school is not a thing being done to you. Two teachers separately tell your parents you have "switched on".' },
      { id: 'stage', label: 'Find the music block and never really leave it',
        fx: { MUS: 12, CRE: 8 }, xp: 145, flag: 'sc_music_block', count: { gigs: 1 },
        result: 'A practice room with a decent mic and nobody watching the booking sheet. You are in there four lunchtimes a week by half term.' },
    ],
  },
  {
    id: 'a13_letchworth', age: 13, scene: 'town',
    intro: 'Letchworth. The first garden city. Wide greens, big trees, room to think.',
    prompt: 'Fourth move. You are very good at this by now.',
    options: [
      { id: 'roots', label: 'Decide this one is home and act like it',
        fx: { HAP: 9, CHA: 6, BIZ: 4 }, xp: 130, flag: 'letchworth_home',
        result: 'You stop treating houses as temporary. You learn the names of people on the road. Something in you settles for the first time since Shillington.' },
      { id: 'network', label: 'Work out who in this town can be useful',
        fx: { BIZ: 11, CHA: 8, SMR: 5 }, xp: 135, flag: 'town_network', count: { deals: 3 },
        result: 'Within two months you know a printer, a bloke with a van, and someone whose dad runs a unit on the industrial estate. Thirteen years old.' },
      { id: 'train', label: 'Find where you can train, every day, without anyone bothering you',
        fx: { ATH: 11, HLT: 6 }, xp: 135, flag: 'training_ground', count: { knights_years: 1 },
        result: 'A stretch of green behind the houses with a wall at one end. You are there at seven every morning before school. Nobody asks you to be.' },
    ],
  },
  {
    id: 'a13_crew_split', age: 13, scene: 'school_high',
    prompt: 'Different schools now. Boyd and the Ollies one way, Jack and Forrest another, and you in the middle as usual.',
    options: [
      { id: 'hold', label: 'Hold the whole group together yourself — weekends, group chat, everything',
        fx: { CHA: 12, HAP: 7, SMR: 4 }, xp: 145, flag: 'group_holder', secret: 'the_glue',
        rel: { boyd: 10, ollie_b: 8, ollie_c: 8, jack: 8, forrest: 8, ollie_hen: 8, oscar: 8 },
        result: 'You are the reason seven people who go to four different schools still see each other every week. It costs you effort nobody ever notices.' },
      { id: 'boyd', label: 'Boyd above all. The rest can be what they are.',
        fx: { HAP: 8, CHA: 5 }, xp: 140, rel: { boyd: 20, ollie_b: 6 }, flag: 'boyd_forever',
        result: 'Some friendships need work. Yours and Boyd\'s has never needed a single minute of it and it is not about to start.' },
      { id: 'new', label: 'Let it breathe and build something new at Saint Chris too',
        fx: { CHA: 9, CRE: 6, SMR: 6 }, xp: 140, flag: 'two_worlds',
        rel: { jack: 6, forrest: 6, oscar: 6 },
        result: 'Two separate lives that only overlap at parties. You get very good at being slightly different in each one, which is a useful and slightly dangerous skill.' },
    ],
  },

  // --------------------------------------------------------------- AGE 14
  {
    id: 'a14_track', age: 14, scene: 'studio',
    intro: 'You have been writing bars since you were three. This is the first time you record one properly.',
    prompt: 'A borrowed mic, a laptop, and a duvet nailed to the wall of your bedroom.',
    options: [
      { id: 'rap', label: 'A rap track. Everything you have been holding back.',
        fx: { MUS: 14, CRE: 9, CHA: 5 }, xp: 160, count: { tracks: 1 }, flag: 'first_track', fame: 4,
        result: 'Two minutes forty. You send it to four people. Within a week two hundred people at Saint Chris have heard it and the head of music has asked who made it.' },
      { id: 'sung', label: 'Sung hooks over the top of your own beat',
        fx: { MUS: 13, CRE: 11, COD: 4 }, xp: 160, count: { tracks: 1 }, flag: 'first_track_sung', fame: 3,
        result: 'You can genuinely sing, it turns out, when nobody is in the room. The hook is the bit everyone can still sing back six years later.' },
      { id: 'both', label: 'Both — verses rapped, chorus sung, all you',
        fx: { MUS: 15, CRE: 10, CHA: 6 }, xp: 175, count: { tracks: 1 }, flag: 'first_track_both',
        fame: 6, secret: 'double_threat',
        result: 'Nobody at school knows anyone who can do both properly. You do both properly on your first ever recording. It changes how people look at you.' },
    ],
  },
  {
    id: 'a14_knights', age: 14, scene: 'pitch',
    prompt: 'Baldock Knights, and a scout from an academy has been at the last three games.',
    options: [
      { id: 'trial', label: 'Take the trial. See how far this actually goes.',
        fx: { ATH: 13, SMR: 5 }, xp: 165, count: { knights_years: 1 }, flag: 'academy_trial',
        result: 'Six weeks in an academy environment. You are not the best there, which has never happened to you before, and it is the most useful thing that has ever happened to you.' },
      { id: 'loyal', label: 'Stay at Baldock. You are not a project, you are their player.',
        fx: { ATH: 11, CHA: 8, HAP: 5 }, xp: 160, count: { knights_years: 1, goals: 14 }, flag: 'knights_loyal',
        result: 'Fourteen goals and a team that would run through a wall for you. The scout keeps coming anyway.' },
      { id: 'terms', label: 'Take the trial, but on your terms — no dropping music or the business',
        fx: { ATH: 10, BIZ: 8, SMR: 8 }, xp: 175, count: { knights_years: 1 }, flag: 'refused_to_narrow', secret: 'wont_be_one_thing',
        result: 'You tell an academy coach, at fourteen, that football is one of three things you do. He does not like it. He also does not withdraw the offer.' },
    ],
  },
  {
    id: 'a14_venture', age: 14, scene: 'workshop',
    prompt: 'You have got a few hundred quid, a laptop, and more ideas than time.',
    options: [
      { id: 'brand', label: 'Start a clothing brand — designs, drops, the lot',
        fx: { BIZ: 13, CRE: 12 }, xp: 170, money: 380, count: { ventures: 1 }, flag: 'clothing_brand',
        result: 'Forty units, sold out in nine days, mostly to people at three different schools. Your margin is better than it has any right to be because you did the designs yourself.' },
      { id: 'agency', label: 'Build websites and edits for local businesses properly',
        fx: { BIZ: 11, COD: 13 }, xp: 170, money: 620, count: { ventures: 1 }, flag: 'agency_seed',
        result: 'Six clients by Christmas. £620. You are turning work away because of double maths, which is an absurd sentence about a fourteen-year-old.' },
      { id: 'events', label: 'Put on events — you already know everybody',
        fx: { BIZ: 12, CHA: 11, MUS: 5 }, xp: 175, money: 290, count: { ventures: 1, gigs: 2 }, flag: 'promoter',
        result: 'A hall, a sound system off a bloke in Hitchin, and 160 teenagers. You clear £290 and learn more about people in one night than in a year of school.' },
    ],
  },

  // --------------------------------------------------------------- AGE 15
  {
    id: 'a15_squeeze', age: 15, scene: 'bedroom',
    intro: 'Football, music, business, GCSEs, and seven friends. Something has to give.',
    prompt: 'You are running on about five hours a night and it is starting to show.',
    options: [
      { id: 'drop', label: 'Drop one thing properly rather than do four things badly',
        fx: { SMR: 10, HLT: 8, HAP: 5 }, xp: 170, flag: 'learned_to_cut',
        result: 'You cut the thing you love third-most, cleanly, with no drama. The other three immediately get better. It is the most adult decision you have made.' },
      { id: 'system', label: 'Build a system — schedule the whole week like a business',
        fx: { BIZ: 10, SMR: 12, HLT: 4 }, xp: 180, flag: 'the_system', secret: 'operator',
        result: 'A colour-coded week, blocked out, defended. You stick to it. Fifteen years old and you are running your own life like an operations manager.' },
      { id: 'push', label: 'Nothing gives. Push through and take the damage.',
        fx: { ATH: 8, BIZ: 8, MUS: 8, HLT: -12, HAP: -4 }, xp: 175, flag: 'burned_hot',
        result: 'You do all four. All four go well. You are also ill for most of February and you sleep for eleven hours a night the entire Easter holiday.' },
    ],
  },
  {
    id: 'a15_gig', age: 15, scene: 'stage',
    prompt: 'First proper gig with an audience that did not come to see you.',
    options: [
      { id: 'own', label: 'All original material. Sink or swim.',
        fx: { MUS: 13, CRE: 9, CHA: 8 }, xp: 180, count: { gigs: 1, tracks: 1 }, fame: 8, flag: 'originals_only',
        result: 'Two hundred people who came for someone else, and you take the room in about ninety seconds. The headliner watches your last three songs from the side.' },
      { id: 'covers', label: 'Win them with covers first, then slip your own in',
        fx: { MUS: 11, SMR: 8, CHA: 9 }, xp: 175, count: { gigs: 1 }, fame: 6, flag: 'smart_setlist',
        result: 'You open with something everyone knows and close with something nobody does, and by then they are yours. Tactically perfect.' },
      { id: 'freestyle', label: 'Freestyle a chunk of it, live, off the room',
        fx: { MUS: 12, CRE: 12, CHA: 10, NAU: 5 }, xp: 195, count: { gigs: 1 }, fame: 10, secret: 'off_the_top',
        result: 'You take three things people shout out and build a verse around them on the spot. It should not work. The clip of it does about 90,000 views by Sunday.' },
    ],
  },
  {
    id: 'a15_naughty', age: 15, scene: 'town',
    prompt: 'Boyd, Ollie B and Ollie C have got hold of a car. None of them can legally drive it.',
    options: [
      { id: 'no', label: 'Absolutely not — and take the keys off them',
        fx: { SMR: 12, CHA: 8, NAU: -6 }, xp: 180, rel: { boyd: 6, ollie_b: 4, ollie_c: 4 }, flag: 'took_the_keys', secret: 'the_one_who_said_no',
        result: 'You are the naughtiest kid any of your teachers have ever met and you are the one who takes the keys. Boyd is furious for two days and thanks you for it at twenty-five.' },
      { id: 'passenger', label: 'Get in. It is a field, not a road.',
        fx: { NAU: 11, HAP: 8, HLT: -4 }, xp: 175, rel: { boyd: 10, ollie_b: 8, ollie_c: 10 }, count: { trouble: 2 },
        result: 'Four laps of a stubble field at dusk in a car worth £300. Nobody dies. Everyone screams. It is one of the best nights of your life and you will never admit that to a parent.' },
      { id: 'flip', label: 'Buy it off them for £80 and sell it on for more',
        fx: { BIZ: 14, NAU: 6, SMR: 7 }, xp: 195, money: 240, count: { deals: 2 }, secret: 'first_flip',
        result: 'You buy a barely-legal car off three fifteen-year-olds, get it cleaned and photographed properly, and sell it for £320. Your first vehicle flip. Not your last.' },
    ],
  },

  // --------------------------------------------------------------- AGE 16
  {
    id: 'a16_gcse', age: 16, scene: 'school_high',
    prompt: 'GCSEs. You have not exactly been a model of academic focus.',
    options: [
      { id: 'graft', label: 'Six weeks of absolute graft and surprise everybody',
        fx: { SMR: 14, HLT: -4 }, xp: 190, flag: 'gcse_strong',
        result: 'You go from predicted middling to genuinely good in six weeks, using the same system you built for your business. Two teachers ask how you did it.' },
      { id: 'targeted', label: 'Ace the ones that matter, coast the rest, spend the time on your own stuff',
        fx: { SMR: 9, BIZ: 10, CRE: 6 }, xp: 195, flag: 'gcse_targeted', money: 400,
        result: 'Strong in the subjects you actually need, comfortably fine everywhere else, and £400 earned during study leave. Ruthless prioritisation, correctly applied.' },
      { id: 'charm', label: 'Get by on natural ability and the sheer goodwill of every teacher you have',
        fx: { CHA: 12, SMR: 6, HAP: 6 }, xp: 185, flag: 'gcse_charm',
        result: 'You revise about eleven hours in total and do fine, largely because three teachers give up their free periods for you without being asked. That is a skill too.' },
    ],
  },
  {
    id: 'a16_fork', age: 16, scene: 'city', multi: true,
    intro: 'Sixteen. Three real talents and a genuine decision starting to form.',
    prompt: 'If you are honest with yourself, which two are you actually betting on?',
    options: [
      { id: 'ball', label: 'Football. You have never not been the best on the pitch.',
        fx: { ATH: 14, HLT: 6 }, xp: 200, flag: 'bet_football', count: { knights_years: 1 },
        result: 'You start training like someone who intends to make a living from it, which is a completely different thing from training hard.' },
      { id: 'mic', label: 'Music. The room goes quiet when you start and you know what that means.',
        fx: { MUS: 14, CRE: 8 }, xp: 200, flag: 'bet_music', fame: 8, count: { tracks: 2 },
        result: 'Two tracks out in a month and the numbers are not small any more. Somebody with an actual job title sends you a message.' },
      { id: 'build', label: 'Business. You have been running things since you were four.',
        fx: { BIZ: 15, SMR: 7 }, xp: 200, flag: 'bet_business', money: 1200, count: { ventures: 1 },
        result: 'You register something properly, with a name and a bank account and a very serious expression in the photo. £1,200 through it in the first quarter.' },
    ],
  },
  {
    id: 'a16_oscar', age: 16, scene: 'stage', requires: (s) => s.flags.joint_birthdays || (s.relationships.oscar ?? 50) > 60,
    prompt: 'Joint sixteenth with Oscar. Same day, same night, sixteen years after the hospital.',
    options: [
      { id: 'big', label: 'Make it the biggest night anybody in your year has put on',
        fx: { CHA: 13, BIZ: 8, HAP: 10 }, xp: 200, rel: { oscar: 18 }, fame: 6, count: { gigs: 1 },
        result: '300 people, a proper sound system, and you and Oscar on the mic at midnight telling the room the hospital story for the ninth time that night.' },
      { id: 'small', label: 'Keep it to the seven of you and do it properly',
        fx: { HAP: 12, CHA: 6 }, xp: 195, flag: 'the_seven', secret: 'the_core',
        rel: { oscar: 16, boyd: 12, ollie_b: 8, ollie_c: 8, jack: 8, forrest: 8, ollie_hen: 8 },
        result: 'Boyd, both other Ollies, Jack, Forrest, Hen and Oscar. One table, one night, no phones. All seven of them are still there at forty.' },
      { id: 'perform', label: 'Perform. Full set. Your birthday, your stage.',
        fx: { MUS: 12, CHA: 10, HAP: 8 }, xp: 205, rel: { oscar: 12 }, fame: 9, count: { gigs: 1, tracks: 1 },
        result: 'You play a forty-minute set at your own birthday and it is the best you have ever been. Oscar introduces you. Somebody films the whole thing on a proper camera.' },
    ],
  },

  // --------------------------------------------------------------- AGE 17
  {
    id: 'a17_wheels', age: 17, scene: 'town',
    prompt: 'Seventeen. Licence. The world just got a lot bigger.',
    options: [
      { id: 'cheap', label: 'Cheapest thing that runs — the money is for the business',
        fx: { BIZ: 11, SMR: 8 }, xp: 195, money: -450, flag: 'sensible_wheels',
        result: 'A £450 hatchback with one working speaker. You do not care. It is a van-shaped hole in your logistics and it just got filled.' },
      { id: 'flip', label: 'Buy, do up, sell, repeat — cars are just another market',
        fx: { BIZ: 14, CRE: 7, SMR: 7 }, xp: 210, money: 1900, count: { deals: 6, ventures: 1 }, flag: 'car_trader', secret: 'the_trade',
        result: 'Four cars in nine months. £1,900 clear. You have found a market you genuinely enjoy and you are unusually good at reading what a thing is worth.' },
      { id: 'nice', label: 'Something that looks the part. Image is a business asset.',
        fx: { CHA: 11, BIZ: 6, HAP: 7 }, xp: 195, money: -1400, fame: 4, flag: 'the_look',
        result: 'It is not sensible and you know it is not sensible. It also gets you into two rooms you would not otherwise have got into, which you had privately calculated.' },
    ],
  },
  {
    id: 'a17_offer', age: 17, scene: 'studio',
    intro: 'Somebody who does this for a living has been watching your numbers.',
    prompt: 'A small label offers you a deal. It is not a big deal. It is a real one.',
    options: [
      { id: 'sign', label: 'Sign it. Money, studio time, people who know what they are doing.',
        fx: { MUS: 13, BIZ: 5, CRE: 6 }, xp: 215, money: 3000, fame: 14, count: { tracks: 4 }, flag: 'signed',
        result: 'Proper studio, proper engineer, proper deadlines. The music gets sharper immediately. You also read every line of that contract twice, which surprises them.' },
      { id: 'refuse', label: 'Turn it down and build your own thing',
        fx: { BIZ: 14, MUS: 10, CRE: 8 }, xp: 225, fame: 9, count: { tracks: 3, ventures: 1 }, flag: 'independent', secret: 'own_the_masters',
        result: 'You keep every master you have ever made. It is slower. It is much harder. Nine years later it turns out to have been worth roughly a house.' },
      { id: 'negotiate', label: 'Negotiate it into something you would actually sign',
        fx: { BIZ: 15, MUS: 10, SMR: 9 }, xp: 235, money: 1800, fame: 11, count: { tracks: 3 }, flag: 'good_deal', secret: 'read_the_contract',
        result: 'You send back a marked-up contract at seventeen years old. They accept two thirds of your changes. Their lawyer asks who is advising you. Nobody is advising you.' },
    ],
  },
  {
    id: 'a17_body', age: 17, scene: 'pitch',
    prompt: 'The football is at a level now where fitness is not automatic any more.',
    options: [
      { id: 'pro', label: 'Train like a professional. Diet, sleep, gym, all of it.',
        fx: { ATH: 14, HLT: 12, HAP: -3 }, xp: 215, count: { knights_years: 1 }, flag: 'pro_habits',
        result: 'You are the fittest player at the club by a distance. You also have to say no to a lot of nights out and it is not as easy as you make it look.' },
      { id: 'balance', label: 'Stay very good without giving up your whole life for it',
        fx: { ATH: 9, HLT: 6, HAP: 9, CHA: 5 }, xp: 210, count: { knights_years: 1, goals: 11 },
        result: 'Eleven goals, out every Saturday night, and still the best one on the pitch. Some people can do this. Almost none of them can.' },
      { id: 'convert', label: 'Turn the athleticism into something that pays — coaching and camps',
        fx: { ATH: 8, BIZ: 13, CHA: 8 }, xp: 220, money: 2400, count: { ventures: 1 }, flag: 'coaching_business',
        result: 'Half-term camps, sixty kids, three of your mates on the payroll. £2,400 in two weeks of school holidays. Your first business with actual employees.' },
    ],
  },

  // --------------------------------------------------------------- AGE 18
  {
    id: 'a18_leaving', age: 18, scene: 'school_high',
    intro: 'Saint Chris ends. Nobody is telling you where to be on Monday ever again.',
    prompt: 'The genuine fork. What do you walk out of that gate towards?',
    options: [
      { id: 'football', label: 'Football, properly, while the window is open',
        fx: { ATH: 16, HLT: 8 }, xp: 260, flag: 'path_football', count: { knights_years: 1 },
        result: 'You give it two years of everything. If it works you will never wonder. If it does not, you will still never wonder, and that is the actual point.' },
      { id: 'music', label: 'Music. Full time. All in.',
        fx: { MUS: 16, CRE: 12 }, xp: 260, fame: 18, count: { tracks: 5 }, flag: 'path_music',
        result: 'No safety net, a bedroom studio and a diary you fill yourself. Six months of nothing, then a track that does not stop.' },
      { id: 'business', label: 'Build the business into something real',
        fx: { BIZ: 17, SMR: 9 }, xp: 260, money: 6000, count: { ventures: 2 }, flag: 'path_business',
        result: 'You skip university entirely and put the whole eighteen years of instinct into one thing. It is terrifying and it is obviously correct.' },
    ],
  },
  {
    id: 'a18_crew_scatter', age: 18, scene: 'town',
    prompt: 'Everyone leaves at once. Uni, apprenticeships, one of them abroad.',
    options: [
      { id: 'anchor', label: 'Be the anchor — the one who always organises it',
        fx: { CHA: 13, HAP: 8 }, xp: 250, flag: 'the_anchor', secret: 'the_glue',
        rel: { boyd: 10, ollie_b: 8, ollie_c: 8, jack: 8, forrest: 8, ollie_hen: 8, oscar: 10 },
        result: 'Twice a year, no excuses, booked eight months out. You are the reason it survives. Twenty years later there is a group chat that has never once gone quiet.' },
      { id: 'hire', label: 'Hire the ones who are up for it',
        fx: { BIZ: 12, CHA: 9 }, xp: 255, money: -2000, flag: 'hired_friends',
        rel: { boyd: 14, ollie_c: 10, forrest: 8 },
        result: 'Boyd on the ground, Forrest on the front end. Working with your mates is either the best decision of your life or the worst, and you find out slowly.' },
      { id: 'go', label: 'Go with them — get out of Hertfordshire for a bit',
        fx: { SMR: 11, CHA: 9, CRE: 9, HAP: 7 }, xp: 255, flag: 'went_away',
        result: 'Eight months somewhere else, doing something unrecognisable. You come back with a completely different sense of how big the thing you are building could be.' },
    ],
  },
  {
    id: 'a18_mario_again', age: 18, scene: 'loft', requires: (s) => s.flags.mario_returns || s.flags.mario_left,
    intro: 'Moving out. Boxes everywhere. Dad hands something down through the loft hatch.',
    prompt: 'Three foot six. Red and blue. Faded now, and squashed on one side.',
    options: [
      { id: 'take', label: 'He comes with you. Non-negotiable.',
        fx: { HAP: 14, CRE: 8 }, xp: 260, flag: 'mario_moves_in', secret: 'still_here',
        result: 'A grown man carries a giant Mario into his first place and stands him in the corner. Everyone who visits asks. Everyone gets the whole story.' },
      { id: 'elowen', label: 'Give him to Elowen', fx: { HAP: 10, CHA: 8 }, xp: 255, rel: { elowen: 22 }, flag: 'mario_to_elowen', secret: 'passed_on',
        result: 'She is sixteen and pretends it is embarrassing. He is in the corner of her room for the next nine years. She takes him to her own first place too.' },
      { id: 'keep_loft', label: 'Back in the loft. He is fine up there.',
        fx: { SMR: 5, HAP: -4 }, xp: 250, flag: 'mario_loft_again',
        result: 'The hatch closes again. You are eighteen and busy and there is genuinely no room. He waits. He is very good at waiting.' },
    ],
  },

  // ------------------------------------------------------------ AGES 19-21
  {
    id: 'a19_first_big', age: 19, scene: 'city',
    prompt: 'The first thing you make that goes properly, unmistakably well.',
    options: [
      { id: 'scale', label: 'Scale it hard and fast while it is hot',
        fx: { BIZ: 15, HLT: -6 }, xp: 270, money: 24000, count: { ventures: 1 }, fame: 8, flag: 'scaled_fast',
        result: 'Twenty-four grand in a year at nineteen. You reinvest almost all of it, which everyone around you thinks is mad and is exactly right.' },
      { id: 'systemise', label: 'Systemise it so it runs without you',
        fx: { BIZ: 13, SMR: 12 }, xp: 280, money: 15000, flag: 'systemised', secret: 'operator',
        result: 'Less money this year. Far more freedom next year. You have understood leverage at nineteen and most people never understand it at all.' },
      { id: 'sell', label: 'Sell it and use the money for something bigger',
        fx: { BIZ: 14, SMR: 9, CRE: 7 }, xp: 275, money: 40000, count: { exits: 1 }, flag: 'first_exit', secret: 'first_exit',
        result: 'Forty grand, cash, at nineteen. Your first exit. You sit in the car afterwards and do not tell anyone for two hours because you want to feel it on your own first.' },
    ],
  },
  {
    id: 'a20_reckoning', age: 20, scene: 'studio',
    prompt: 'You cannot be a professional footballer, a recording artist and a founder. Not all three. Not properly.',
    options: [
      { id: 'one', label: 'Pick the one and be genuinely great at it',
        fx: { SMR: 12, HAP: 6 }, xp: 285, flag: 'picked_one',
        result: 'You go all in on one and let the other two become things you love rather than things you owe. Within eighteen months you are better at it than you have ever been at anything.' },
      { id: 'stack', label: 'Stack them — make them feed each other instead of compete',
        fx: { BIZ: 13, CRE: 13, CHA: 8 }, xp: 300, fame: 12, flag: 'stacked', secret: 'wont_be_one_thing',
        result: 'The audience from the music buys from the business. The business funds the studio. The athleticism keeps you standing. It should not work as well as it does.' },
      { id: 'two', label: 'Two of them, at full power. Drop the third for good.',
        fx: { HAP: -5, SMR: 10, BIZ: 8, MUS: 8 }, xp: 290, flag: 'dropped_one',
        result: 'You put one of them down properly and it hurts for about a year. Then it stops hurting and the other two get twice as good.' },
    ],
  },
  {
    id: 'a21_love', age: 21, scene: 'city',
    prompt: 'Twenty-one. Someone who is genuinely, seriously good for you.',
    options: [
      { id: 'all_in', label: 'All in. Make room for it.',
        fx: { HAP: 15, HLT: 6, CHA: 6 }, xp: 290, flag: 'partner', rel: { partner: 70 },
        result: 'You are not good at making room, historically. You make room. It turns out to be the single best decision of your twenties.' },
      { id: 'slow', label: 'Take it slowly — you have a lot on',
        fx: { SMR: 8, HAP: 6, BIZ: 6 }, xp: 285, flag: 'partner_slow', rel: { partner: 55 },
        result: 'It works, quietly, in the gaps. Slower than it should be, but nothing gets broken by being rushed.' },
      { id: 'work', label: 'The work comes first right now and you are honest about that',
        fx: { BIZ: 12, MUS: 8, HAP: -8 }, xp: 285, flag: 'chose_work',
        result: 'You say it out loud rather than let it happen by neglect, which is at least fair to both of you. It still costs you something you notice later.' },
    ],
  },
];
