// Scripted beats, ages 0-12. Every question offers three written choices; the
// engine always appends a fourth "make your own" slot.
//
// fx      stat deltas (positive gains are multiplied by talent)
// xp      experience for taking that option
// flag    storyline switch to set
// count   counters to bump
// rel     relationship nudges
// money   pocket money / earnings in pounds
// result  the line of narration shown after you choose

export const EARLY = [
  // ---------------------------------------------------------------- AGE 0
  {
    id: 'a0_music', age: 0, scene: 'nursery', multi: true,
    intro: 'Shillington. You are three weeks old and Dad has already wired the speakers into the front room.',
    prompt: 'David puts a record on for you. What gets into your bones first?',
    options: [
      { id: 'lp', label: 'Linkin Park — the loud, hurt, brilliant stuff',
        fx: { MUS: 5, CRE: 4, HAP: 3 }, xp: 30, flag: 'music_rock',
        result: 'Hybrid Theory at low volume in a Bedfordshire nursery. You stop crying the moment the guitars come in. Alex is baffled. David is delighted.' },
      { id: 'em', label: 'Eminem — clean versions, every word of them',
        fx: { MUS: 5, CHA: 3, SMR: 2 }, xp: 30, flag: 'music_rap',
        result: 'Clean edits only, and even then Mum raises an eyebrow. But you go still and listen like it is a language you already half know.' },
      { id: 'pac', label: '2Pac and Biggie — the old heavyweights',
        fx: { MUS: 5, CRE: 3, CHA: 3 }, xp: 30, flag: 'music_hiphop',
        result: 'California Love and Juicy on repeat. You are eleven pounds of human being nodding roughly on the beat. Dad calls Mum in to watch.' },
    ],
  },
  {
    id: 'a0_calm', age: 0, scene: 'nursery',
    intro: 'You are, by every account, an easy baby. No screaming through the night. Dry every morning. No Ninjamas in this house.',
    prompt: 'Three in the morning. You are wide awake and completely content. What do you do with the quiet?',
    options: [
      { id: 'watch', label: 'Lie there and watch the room like you are learning it',
        fx: { SMR: 4, HAP: 2 }, xp: 25, flag: 'watcher',
        result: 'You map the ceiling crack, the curtain gap, the exact stripe of landing light. You are gathering information. You will do this your whole life.' },
      { id: 'babble', label: 'Babble along to whatever was on the stereo earlier',
        fx: { MUS: 4, CHA: 3 }, xp: 25, flag: 'early_rhythm',
        result: 'Not words. Rhythm. Alex stands in the doorway at 3am listening to her baby scat a hook back at an empty room.' },
      { id: 'sleep', label: 'Sleep straight through until seven, like a legend',
        fx: { HLT: 5, HAP: 4 }, xp: 25, flag: 'sleeper',
        result: 'Twelve hours. Dry. Every night. Other parents ask Alex what her secret is and she genuinely has no idea.' },
    ],
  },
  {
    id: 'a0_reach', age: 0, scene: 'home',
    prompt: 'First thing you ever properly reach for and refuse to let go of.',
    options: [
      { id: 'ball', label: 'A football, obviously', fx: { ATH: 6, HAP: 2 }, xp: 30, flag: 'ball_first',
        result: 'It is bigger than your head. You get both arms round it and scream when anyone tries to take it back.' },
      { id: 'coin', label: 'Dad\'s loose change off the coffee table', fx: { BIZ: 6, SMR: 2 }, xp: 30, flag: 'coin_first',
        result: 'Not the shiny toy. The money. Alex says "that is a sign" and she is not joking, and she is not wrong.' },
      { id: 'mic', label: 'The TV remote, held like a microphone', fx: { MUS: 5, CHA: 3 }, xp: 30, flag: 'mic_first',
        result: 'You do not press the buttons. You hold it up to your face and shout at the room. Everyone in it applauds.' },
    ],
  },

  // ---------------------------------------------------------------- AGE 1
  {
    id: 'a1_kickers', age: 1, scene: 'pitch',
    intro: 'Little Kickers. A church hall, eleven toddlers, and a lot of falling over. You are not falling over.',
    prompt: 'Your first ever session. The coach rolls a ball into the middle.',
    options: [
      { id: 'take', label: 'Take it and go. Straight through the lot of them.',
        fx: { ATH: 8, CHA: 3, NAU: 2 }, xp: 45, flag: 'kickers_star', count: { goals: 3 },
        result: 'Three goals in your first hour of organised football. The coach stops the session to point at you. The other parents go very quiet.' },
      { id: 'pass', label: 'Pass it to the smallest kid there',
        fx: { CHA: 6, ATH: 4, HAP: 3 }, xp: 45, flag: 'kickers_captain',
        result: 'You are one year old and you have just made an assist out of pure kindness. Somebody\'s mum actually gets emotional.' },
      { id: 'keepy', label: 'Try to keep it up. Fail. Try again. Fail. Keep going.',
        fx: { ATH: 6, SMR: 3, HAP: 2 }, xp: 45, flag: 'grafter',
        result: 'Forty minutes, one touch at a time. You do not get bored and you do not stop. That turns out to be the whole personality.' },
    ],
  },
  {
    id: 'a1_boyd', age: 1, scene: 'garden',
    intro: 'Boyd has been in your life since before either of you had names for each other.',
    prompt: 'Boyd points at the top of the garden slide. Neither of you can properly walk yet.',
    options: [
      { id: 'go', label: 'Go up it. Obviously go up it.',
        fx: { NAU: 8, ATH: 5, HAP: 4 }, xp: 45, rel: { boyd: 10 }, flag: 'first_trouble',
        result: 'Two toddlers at the top of a slide meant for four-year-olds. Alex arrives at a sprint. Boyd goes down head first. You go down laughing.' },
      { id: 'watch', label: 'Let Boyd go first and watch what happens',
        fx: { SMR: 6, NAU: 3 }, xp: 45, rel: { boyd: 4 }, flag: 'watcher',
        result: 'Boyd hits the grass at speed. You take notes. This becomes the arrangement for roughly the next twenty years.' },
      { id: 'both', label: 'Both of you. At the same time. On the same slide.',
        fx: { NAU: 7, CHA: 5, HAP: 5 }, xp: 50, rel: { boyd: 14 }, flag: 'boyd_pact',
        result: 'Physically it does not work. Emotionally it works perfectly. You are a unit from this moment on.' },
    ],
  },
  {
    id: 'a1_home_ball', age: 1, scene: 'home',
    prompt: 'The ball is in the house. The house has a lamp in it. Alex has said the word "outside" twice.',
    options: [
      { id: 'shoot', label: 'Shoot anyway', fx: { NAU: 6, ATH: 5 }, xp: 40, count: { trouble: 1 },
        result: 'The lamp survives. The plant does not. You are carried outside mid-celebration.' },
      { id: 'outside', label: 'Take it outside like a professional', fx: { ATH: 6, SMR: 3, HAP: 2 }, xp: 40,
        result: 'You lug a ball bigger than you through the back door on your own. Alex watches from the window and quietly loses it.' },
      { id: 'dribble', label: 'Dribble it round the furniture instead of shooting', fx: { ATH: 7, CRE: 4 }, xp: 45, flag: 'close_control',
        result: 'Sofa, table leg, dog bed, back again. Your close control is being built in a Shillington living room.' },
    ],
  },

  // ---------------------------------------------------------------- AGE 2
  {
    id: 'a2_elowen', age: 2, scene: 'home',
    intro: 'Alex comes home with Elowen. Your sister. Suddenly you are not the only one.',
    prompt: 'They put her down on the sofa next to you.',
    options: [
      { id: 'guard', label: 'Sit next to her and refuse to move all afternoon',
        fx: { HAP: 6, CHA: 4 }, xp: 50, rel: { elowen: 20 }, flag: 'big_brother',
        result: 'You do not want to hold her. You want to sit guard over her. You stay there until you fall asleep against the arm of the sofa.' },
      { id: 'show', label: 'Immediately perform for her — the full routine',
        fx: { MUS: 5, CHA: 6, HAP: 4 }, xp: 50, rel: { elowen: 14 }, flag: 'performer',
        result: 'A two-year-old rapping nonsense at a newborn. She cannot focus her eyes yet. You have found your first audience anyway.' },
      { id: 'test', label: 'Test whether she can hold a football', fx: { NAU: 6, ATH: 3, HAP: 3 }, xp: 50, rel: { elowen: 8 },
        result: 'She cannot. You establish this scientifically, twice, before anyone stops you.' },
    ],
  },
  {
    id: 'a2_sharks', age: 2, scene: 'pitch',
    intro: 'Shillington Sharks. Your club for the next eight years.',
    prompt: 'First training session with the Sharks. You are the youngest there by a distance.',
    options: [
      { id: 'front', label: 'Get straight to the front of every drill',
        fx: { ATH: 7, CHA: 4, NAU: 2 }, xp: 55, flag: 'sharks_front', count: { sharks_years: 1 },
        result: 'You elbow your way to the front of the queue for every single drill. The older boys are annoyed for about ten minutes, then they are impressed.' },
      { id: 'learn', label: 'Hang back, watch the good ones, copy them exactly',
        fx: { ATH: 5, SMR: 5 }, xp: 55, flag: 'student_of_game', count: { sharks_years: 1 },
        result: 'You spend the session shadowing the best player there, step for step. By the end you are doing his turn better than he is.' },
      { id: 'mates', label: 'Get Boyd signed up too, immediately',
        fx: { CHA: 6, ATH: 4, HAP: 4 }, xp: 55, rel: { boyd: 10 }, count: { sharks_years: 1 }, flag: 'boyd_sharks',
        result: 'You will not stop asking until Boyd\'s mum gives in. Sharks now have both of you. The coaching staff have no idea what is coming.' },
    ],
  },
  {
    id: 'a2_pool', age: 2, scene: 'pool',
    intro: 'Swimming lessons start this year and run all the way to nine.',
    prompt: 'First time in the big pool. The instructor asks who wants to go first.',
    options: [
      { id: 'jump', label: 'Jump in before she finishes the sentence',
        fx: { ATH: 6, NAU: 5, HAP: 4 }, xp: 50, flag: 'no_fear_water', count: { swim_years: 1 },
        result: 'You are in the water before the question mark. You come up grinning. She has to fish you out and explain the concept of waiting.' },
      { id: 'technique', label: 'Watch her demonstrate properly first, then go',
        fx: { ATH: 5, SMR: 4 }, xp: 50, count: { swim_years: 1 }, flag: 'technical_swimmer',
        result: 'You copy the arm shape exactly. Two lessons in you are moved up a group.' },
      { id: 'race', label: 'Ask if you can race someone', fx: { ATH: 6, CHA: 4, NAU: 2 }, xp: 50, flag: 'racer', count: { swim_years: 1 },
        result: 'You are two years old and your first question in a swimming pool is whether there is a winner. There is now.' },
    ],
  },

  // ---------------------------------------------------------------- AGE 3
  {
    id: 'a3_deal', age: 3, scene: 'garden',
    intro: 'Nobody taught you this. It just started happening.',
    prompt: 'Ollie has a toy car you want. You have a packet of raisins.',
    options: [
      { id: 'trade', label: 'Trade — but get the raisins back after',
        fx: { BIZ: 9, SMR: 4, NAU: 4 }, xp: 60, flag: 'first_deal', count: { deals: 1 },
        result: 'The trade completes. Ten minutes later you have the car AND the raisins and Ollie cannot explain how. Your first ever deal and you cheated slightly.' },
      { id: 'fair', label: 'Straight swap, no funny business',
        fx: { BIZ: 6, CHA: 5, HAP: 3 }, xp: 60, flag: 'first_deal', count: { deals: 1 }, rel: { ollie_a: 10 },
        result: 'A clean, honest swap at three years old. Ollie trusts you completely after this, which is worth more than the car.' },
      { id: 'build', label: 'Refuse to trade — offer to build him a better one',
        fx: { CRE: 8, BIZ: 5 }, xp: 60, flag: 'builder', count: { builds: 1 },
        result: 'You make him a car out of two blocks and a bottle cap. He likes it more than his actual car. You have just invented your entire business model.' },
    ],
  },
  {
    id: 'a3_nursery', age: 3, scene: 'school_lower',
    prompt: 'Nursery. Twenty small people and one carpet. Who do you become in here?',
    options: [
      { id: 'ringleader', label: 'The one everyone follows', fx: { CHA: 8, NAU: 6 }, xp: 55, flag: 'ringleader',
        result: 'Within a week the entire carpet does what you do. The staff use the phrase "strong personality" on a form.' },
      { id: 'entertainer', label: 'The one who makes everyone laugh', fx: { CHA: 6, MUS: 4, HAP: 5 }, xp: 55, flag: 'entertainer',
        result: 'You work out that a room laughing feels better than a room quiet, and you never really unlearn it.' },
      { id: 'floater', label: 'Everywhere and nowhere — in with all of them',
        fx: { CHA: 5, SMR: 4, HAP: 4 }, xp: 55, flag: 'ambivert',
        result: 'Loud group in the morning, on your own with the blocks after lunch, back out for the football. Both settings, always have been.' },
    ],
  },
  {
    id: 'a3_music2', age: 3, scene: 'home', multi: true,
    prompt: 'You know all the words now. Clean versions, but all of them. What do you do with that?',
    options: [
      { id: 'perform', label: 'Perform the whole thing for the family, standing on the coffee table',
        fx: { MUS: 7, CHA: 6, NAU: 3 }, xp: 60, flag: 'coffee_table_gig', count: { gigs: 1 },
        result: 'Full Eminem verse, word perfect, delivered from the coffee table to four adults and a baby. Dad films it. That video never dies.' },
      { id: 'write', label: 'Start making up your own words over the top',
        fx: { MUS: 6, CRE: 7 }, xp: 65, flag: 'first_bars', count: { bars: 1 },
        result: 'You do not just copy it. You replace the second verse with a verse about your sister. It scans. It actually scans.' },
      { id: 'sing', label: 'Sing the hooks properly instead of rapping them',
        fx: { MUS: 7, HAP: 4 }, xp: 60, flag: 'can_sing',
        result: 'Turns out you can hold a tune, cleanly, with no training whatsoever. Alex stops what she is doing in the kitchen.' },
    ],
  },

  // ---------------------------------------------------------------- AGE 4
  {
    id: 'a4_school', age: 4, scene: 'school_lower',
    intro: 'Shillington Lower School. Reception class.',
    prompt: 'Day one. There is a boy on the climbing frame who has clearly been told to get off it.',
    options: [
      { id: 'join', label: 'Get up there with him', fx: { NAU: 8, ATH: 5, CHA: 4 }, xp: 60,
        flag: 'met_ollie_b', rel: { ollie_b: 18 }, count: { trouble: 1 },
        result: 'That is Ollie B. You are both down off the frame within ninety seconds and best mates within five minutes. The teacher writes both names down on day one.' },
      { id: 'talk', label: 'Talk him down before he gets caught', fx: { CHA: 7, SMR: 5 }, xp: 60,
        flag: 'met_ollie_b', rel: { ollie_b: 12 },
        result: 'You get Ollie B down about four seconds before Mrs Wright turns round. He owes you one, and he knows it.' },
      { id: 'ball', label: 'Ignore it — there is a football on the field', fx: { ATH: 8, HAP: 3 }, xp: 60,
        flag: 'met_ollie_b', rel: { ollie_b: 6 },
        result: 'You find the only football on the field. By lunch, Ollie B has come to find you, because that is where the game is.' },
    ],
  },
  {
    id: 'a4_mario', age: 4, scene: 'bedroom',
    intro: 'It arrives in a box the size of a wardrobe. Three foot six of soft, grinning, red-and-blue Mario. He is nearly as tall as you.',
    prompt: 'Mario is standing in the corner of your room. What is he?',
    options: [
      { id: 'friend', label: 'He is a person. He gets a side of the bed.',
        fx: { HAP: 8, CRE: 6 }, xp: 70, flag: 'mario_friend',
        result: 'Mario sleeps in the bed. Mario comes downstairs for breakfast. Mario has opinions, which you supply. This lasts two solid years.' },
      { id: 'teammate', label: 'He is a defender. You have found a permanent training partner.',
        fx: { ATH: 7, CRE: 5, HAP: 5 }, xp: 70, flag: 'mario_teammate',
        result: 'Mario stands in the garden and you go past him nine thousand times. He never once dives in. Best defender you will ever face.' },
      { id: 'audience', label: 'He is the crowd. Every show needs one.',
        fx: { MUS: 6, CRE: 6, HAP: 5 }, xp: 70, flag: 'mario_audience',
        result: 'You perform full sets to a three-foot-six plumber, every night, for two years. He never leaves early.' },
    ],
  },
  {
    id: 'a4_playground', age: 4, scene: 'school_lower',
    prompt: 'You have noticed something: everyone wants the good stickers, and nobody has as many as you.',
    options: [
      { id: 'sell', label: 'Set up a swap shop at the bottom of the field',
        fx: { BIZ: 10, CHA: 5, NAU: 3 }, xp: 70, flag: 'playground_shop', count: { deals: 2, ventures: 1 }, money: 2,
        result: 'A functioning economy behind the bins by Wednesday. You are four. A dinner lady eventually shuts it down and you appeal the decision.' },
      { id: 'give', label: 'Give the best ones away and see what comes back',
        fx: { CHA: 9, BIZ: 5, HAP: 4 }, xp: 70, flag: 'generous_operator',
        result: 'You hand out the rarest ones for free. Within a fortnight people are bringing you things unprompted. You have accidentally discovered goodwill.' },
      { id: 'corner', label: 'Quietly buy up every single shiny one first',
        fx: { BIZ: 11, SMR: 5, NAU: 4 }, xp: 75, flag: 'cornered_market', count: { deals: 3 },
        result: 'You corner the shiny sticker market at the age of four. Prices triple. Somebody\'s dad hears about it and does not know whether to laugh.' },
    ],
  },

  // ---------------------------------------------------------------- AGE 5
  {
    id: 'a5_blake', age: 5, scene: 'home',
    intro: 'Blake is born. Another cousin, another girl, and you are the big one now.',
    prompt: 'You are allowed to hold her if you sit down and keep both arms still.',
    options: [
      { id: 'hold', label: 'Sit dead still for eleven minutes', fx: { HAP: 6, SMR: 4 }, xp: 55, rel: { blake: 18 },
        result: 'You do not move a muscle. You barely breathe. Someone takes a photo that stays on a fridge for fifteen years.' },
      { id: 'teach', label: 'Immediately start telling her how things work round here',
        fx: { CHA: 7, HAP: 4, NAU: 3 }, xp: 55, rel: { blake: 12 }, flag: 'the_explainer',
        result: 'A five-year-old briefing a newborn on the rules of the garden. She sleeps through the entire induction.' },
      { id: 'sing', label: 'Sing to her — properly, the clean hook',
        fx: { MUS: 6, HAP: 6 }, xp: 60, rel: { blake: 20 }, flag: 'lullaby',
        result: 'You give a three-week-old baby an acoustic version of a 2Pac hook. It works. She goes out like a light. The room does not know where to look.' },
    ],
  },
  {
    id: 'a5_mario2', age: 5, scene: 'garden', requires: (s) => s.flags.mario_friend || s.flags.mario_teammate || s.flags.mario_audience,
    prompt: 'Year two of Mario. He has been outside, upstairs, in the car and briefly in the pond. What is the big adventure?',
    options: [
      { id: 'expedition', label: 'Carry him all the way to the top of the village',
        fx: { ATH: 6, CRE: 6, HAP: 6 }, xp: 65, flag: 'mario_expedition',
        result: 'Three foot six of plumber, dragged up past the church by a five-year-old. Two separate cars slow down. You get him to the top. You both look at the fields.' },
      { id: 'tournament', label: 'Run a full tournament in the garden with Mario in goal',
        fx: { ATH: 7, BIZ: 5, CRE: 5 }, xp: 65, flag: 'mario_tournament', count: { ventures: 1 },
        result: 'Six kids, a fixture list drawn in chalk, and an immovable keeper. You charge one sweet for entry. Nobody questions it.' },
      { id: 'stage', label: 'Build him a stage and headline your own show',
        fx: { MUS: 7, CRE: 7, CHA: 4 }, xp: 70, flag: 'mario_stage', count: { gigs: 1 },
        result: 'Cardboard stage, kitchen torch for a spotlight, Mario front row centre. Alex, David, Elowen and a plumber. Sold out.' },
    ],
  },
  {
    id: 'a5_sportsday', age: 5, scene: 'school_lower',
    prompt: 'Sports day. Sack race, sprint, and the long one round the field. You cannot enter all three... officially.',
    options: [
      { id: 'sprint', label: 'Sprint. Win it by a stupid distance.',
        fx: { ATH: 9, CHA: 4 }, xp: 70, flag: 'fastest_in_year', count: { wins: 1 },
        result: 'You cross the line while second place is still in the middle third. A parent audibly says "who is that?"' },
      { id: 'distance', label: 'The long one — nobody your age paces it and you will',
        fx: { ATH: 8, SMR: 5 }, xp: 70, count: { wins: 1 }, flag: 'engine',
        result: 'Everyone sets off flat out and dies. You do not. You go past the whole field on the last bend without changing pace.' },
      { id: 'all', label: 'Enter all three anyway and dare anyone to stop you',
        fx: { ATH: 7, NAU: 7, CHA: 5 }, xp: 75, count: { wins: 2, trouble: 1 }, flag: 'unstoppable',
        result: 'You win two, come second in the sack race because you are exhausted, and get a stern word about the entry rules. Worth it.' },
    ],
  },

  // ---------------------------------------------------------------- AGE 6
  {
    id: 'a6_mario_last', age: 6, scene: 'bedroom',
    intro: 'Something shifts this year. You do not decide it. It just happens.',
    prompt: 'Mario is still in the corner. You have not spoken to him in a fortnight.',
    options: [
      { id: 'loft', label: 'Help Dad put him up in the loft "for now"',
        fx: { SMR: 4, HAP: -3 }, xp: 65, flag: 'mario_loft', count: { mario_years: 2 },
        result: 'You hand him up through the hatch yourself. The hatch closes. You are six, and you genuinely do not think about him again for four years.' },
      { id: 'corner', label: 'Leave him in the corner and quietly stop noticing him',
        fx: { CRE: 3 }, xp: 65, flag: 'mario_loft', count: { mario_years: 2 },
        result: 'He stays in the corner for months, gathering a coat, then a bag, then a pile of kit. One day Alex moves him to the loft and you do not even ask where he went.' },
      { id: 'goodbye', label: 'Say a proper goodbye first, out loud, like an idiot',
        fx: { HAP: 4, CRE: 5 }, xp: 75, flag: 'mario_loft', count: { mario_years: 2 }, secret: 'mario_goodbye',
        result: 'You tell a soft toy that you will see him later. You mean it as a formality. It turns out to be a promise, and it takes four years to keep.' },
    ],
  },
  {
    id: 'a6_trouble', age: 6, scene: 'school_lower',
    prompt: 'Boyd and Ollie B have a plan involving the staff room door and a whoopee cushion.',
    options: [
      { id: 'in', label: 'In. Completely in.', fx: { NAU: 9, CHA: 5, HAP: 5 }, xp: 65,
        count: { trouble: 2 }, rel: { boyd: 8, ollie_b: 8 }, flag: 'the_three',
        result: 'It works far better than any of you expected. All three of you are outside the head\'s office by 10:40. All three of you are still laughing.' },
      { id: 'improve', label: 'In, but make the plan actually good first',
        fx: { NAU: 7, SMR: 6, CRE: 5 }, xp: 75, count: { trouble: 1 }, rel: { boyd: 10, ollie_b: 10 }, flag: 'the_brains',
        result: 'You fix the timing, the placement and the alibi. Nobody gets caught. From here on, they bring you the plans before they run them.' },
      { id: 'out', label: 'Out — you have a football match at lunch',
        fx: { ATH: 6, SMR: 4, NAU: -3 }, xp: 65,
        result: 'You genuinely choose football over chaos. It happens perhaps four times in your entire childhood and this is one of them.' },
    ],
  },
  {
    id: 'a6_reading', age: 6, scene: 'home',
    prompt: 'Rainy Sunday. Nothing on. Nobody about.',
    options: [
      { id: 'computer', label: 'Get on the family computer and start clicking things',
        fx: { COD: 8, SMR: 5, CRE: 4 }, xp: 70, flag: 'computer_curious',
        result: 'You find things nobody showed you. You break two things and fix one. Something about it clicks in a way school never has.' },
      { id: 'lyrics', label: 'Write a full page of your own bars', fx: { MUS: 8, CRE: 6 }, xp: 70, count: { bars: 3 }, flag: 'writing_bars',
        result: 'Half of it does not scan. The other half is better than it has any right to be from a six-year-old with a Biro.' },
      { id: 'plan', label: 'Draw up a business, properly, with prices',
        fx: { BIZ: 9, CRE: 6, SMR: 3 }, xp: 75, count: { ventures: 1 }, flag: 'business_plans',
        result: 'Car washing. Four price tiers. A logo. A rough map of the street with the good cars circled. You are six.' },
    ],
  },

  // ---------------------------------------------------------------- AGE 7
  {
    id: 'a7_scratch', age: 7, scene: 'bedroom',
    intro: 'Somebody at school shows you Scratch. Coloured blocks that snap together and make a cat do things.',
    prompt: 'Two hours in, you have got the cat walking. What do you build?',
    options: [
      { id: 'game', label: 'A game. A proper one, with levels and a score.',
        fx: { COD: 11, CRE: 8, SMR: 5 }, xp: 85, flag: 'scratch_games', count: { scratch_projects: 1 },
        result: 'Three levels, a health bar and a boss that is far too hard. You show it to your teacher and she has to go and get another teacher.' },
      { id: 'football', label: 'A football game with you and Boyd in it',
        fx: { COD: 10, CRE: 7, ATH: 2 }, xp: 85, flag: 'scratch_games', count: { scratch_projects: 1 }, rel: { boyd: 8 },
        result: 'Two sprites, one net, and a physics engine you have invented from first principles and is completely wrong in a fun way.' },
      { id: 'music', label: 'A music thing — beats you can trigger with the keys',
        fx: { COD: 10, MUS: 7, CRE: 6 }, xp: 90, flag: 'scratch_music', count: { scratch_projects: 1 },
        result: 'You have built a sampler out of a children\'s coding tool. It is genuinely a sampler. You use it for actual bars.' },
    ],
  },
  {
    id: 'a7_sharks_match', age: 7, scene: 'pitch',
    prompt: 'Sharks are 2-1 down with ten minutes left. The ball comes to you on the halfway line.',
    options: [
      { id: 'solo', label: 'Go. All of them. Right now.',
        fx: { ATH: 9, CHA: 5, NAU: 3 }, xp: 80, count: { goals: 2, wins: 1 }, flag: 'the_run',
        result: 'Past four, round the keeper, and then you do it again five minutes later. 3-2. Parents on the touchline are shouting things they will be embarrassed about later.' },
      { id: 'team', label: 'Play the pass and drag the whole team up the pitch with you',
        fx: { ATH: 6, CHA: 8, SMR: 5 }, xp: 80, count: { wins: 1, assists: 2 }, flag: 'captain_material',
        result: 'Two assists in seven minutes and a team that suddenly believes. The coach makes you captain the following Saturday.' },
      { id: 'shoot', label: 'Hit it from the halfway line', fx: { ATH: 7, CRE: 6, NAU: 4 }, xp: 85, count: { goals: 1 }, flag: 'audacity',
        result: 'It goes in. From the halfway line. Under-8s football is not ready for it and honestly neither are you. Someone\'s dad films the celebration, not the goal.' },
    ],
  },
  {
    id: 'a7_venture', age: 7, scene: 'village',
    prompt: 'You want money that is actually yours. Shillington is small but it is not nothing.',
    options: [
      { id: 'cars', label: 'Wash cars up and down the road', fx: { BIZ: 9, ATH: 4, CHA: 5 }, xp: 80, money: 22, count: { ventures: 1 },
        result: 'Nine cars, two Saturdays, twenty-two quid. You reinvest four of it in a better sponge, which is the single most telling thing about you.' },
      { id: 'tuck', label: 'Buy sweets in bulk and sell them at school',
        fx: { BIZ: 12, NAU: 6, SMR: 4 }, xp: 90, money: 31, count: { ventures: 1, trouble: 1 }, flag: 'tuck_baron',
        result: 'Margin of about 400%. It runs for six glorious weeks before a teacher works out where the sugar is coming from. You are asked to stop. You negotiate.' },
      { id: 'coach', label: 'Charge the younger kids for football coaching',
        fx: { BIZ: 8, ATH: 6, CHA: 7 }, xp: 85, money: 15, count: { ventures: 1 }, flag: 'young_coach',
        result: 'Fifty pence a session, six kids, in the field behind the houses. Two of their parents say it is the best coaching their kid has had. They are not entirely joking.' },
    ],
  },

  // ---------------------------------------------------------------- AGE 8
  {
    id: 'a8_move', age: 8, scene: 'town',
    intro: 'The family moves to Hitchin. Bigger, busier, and forty minutes from everything you know.',
    prompt: 'First week in a market town after eight years in a village.',
    options: [
      { id: 'explore', label: 'Learn the whole town on foot in a fortnight',
        fx: { SMR: 7, ATH: 5, CHA: 4 }, xp: 80, flag: 'knows_hitchin',
        result: 'Every alley, every shortcut, which shop lets you in with muddy boots. You build a map of Hitchin in your head and never lose it.' },
      { id: 'keep', label: 'Make absolutely sure nothing changes with Boyd',
        fx: { CHA: 7, HAP: 6 }, xp: 80, rel: { boyd: 16, ollie_b: 8 }, flag: 'loyal',
        result: 'You are on the phone constantly and back in Shillington every weekend for Sharks. The move does not cost you a single friend, which takes real effort at eight.' },
      { id: 'opportunity', label: 'Spot that a bigger town means bigger customers',
        fx: { BIZ: 10, SMR: 5 }, xp: 85, flag: 'town_ambition', count: { ventures: 1 }, money: 18,
        result: 'More houses, more cars, more doors. You are running a bigger round within a month. Shillington was the pilot. Hitchin is the rollout.' },
    ],
  },
  {
    id: 'a8_willa', age: 8, scene: 'home',
    intro: 'Willa is born. Quiet from the start, and watching everything.',
    prompt: 'She is the third cousin and she does not make a sound.',
    options: [
      { id: 'gentle', label: 'Match her energy — go quiet and just sit with her',
        fx: { SMR: 6, HAP: 5, CHA: 4 }, xp: 60, rel: { willa: 20 }, flag: 'ambivert_proof',
        result: 'The loudest kid in the family sits in total silence with a sleeping baby for half an hour. Both settings, always have been.' },
      { id: 'full', label: 'Give her the full show anyway', fx: { CHA: 6, MUS: 5, HAP: 4 }, xp: 60, rel: { willa: 10 },
        result: 'She stares at you throughout with an expression that is, honestly, quite critical. You respect it.' },
      { id: 'promise', label: 'Decide, privately, that you will always look out for her',
        fx: { HAP: 6, CHA: 5 }, xp: 70, rel: { willa: 24 }, secret: 'quiet_promise',
        result: 'Nobody hears you make it and you never mention it. You keep it for the next eighty years.' },
    ],
  },
  {
    id: 'a8_scratch2', age: 8, scene: 'bedroom', requires: (s) => (s.counters.scratch_projects || 0) > 0,
    prompt: 'Your Scratch stuff is getting shared around school. Someone asks if you can make one for them.',
    options: [
      { id: 'charge', label: 'Yes — but it costs', fx: { BIZ: 10, COD: 8 }, xp: 90, money: 12,
        count: { scratch_projects: 2, ventures: 1 }, flag: 'code_for_money', secret: 'first_paid_code',
        result: 'Two pounds a game. You take four orders. You are eight years old and you have just been paid for software.' },
      { id: 'teach', label: 'No — but you will teach them how',
        fx: { COD: 9, CHA: 8, SMR: 5 }, xp: 90, count: { scratch_projects: 1 }, flag: 'scratch_teacher',
        result: 'You run an unofficial club at lunch. Six kids, one computer, you at the keyboard explaining loops. A teacher watches from the door and does not interrupt.' },
      { id: 'bigger', label: 'Ignore the request and go build something far more ambitious',
        fx: { COD: 12, CRE: 9 }, xp: 95, count: { scratch_projects: 3 }, flag: 'scratch_ambition',
        result: 'A twelve-level platformer with a save system you have hand-built out of variables. It takes two months. It is genuinely impressive.' },
    ],
  },

  // ---------------------------------------------------------------- AGE 9
  {
    id: 'a9_rba', age: 9, scene: 'school_mid',
    intro: 'Robert Bloomfield Academy. Middle school. Bigger fish, bigger pond.',
    prompt: 'New school, nobody knows you. What is the first impression?',
    options: [
      { id: 'sport', label: 'The one who is unbelievable at sport',
        fx: { ATH: 9, CHA: 6 }, xp: 85, flag: 'rba_athlete',
        result: 'You are picked for three teams in the first fortnight. It becomes the thing people know about you before they know your name.' },
      { id: 'funny', label: 'The one who is very funny and slightly dangerous',
        fx: { CHA: 9, NAU: 7, HAP: 4 }, xp: 85, flag: 'rba_wildcard',
        result: 'Two detentions and a reputation inside a month. People want to sit near you. Teachers want you at the front.' },
      { id: 'quiet', label: 'Give it a fortnight, watch the room, then move',
        fx: { SMR: 8, CHA: 6 }, xp: 90, flag: 'rba_strategist',
        result: 'You spend two weeks working out exactly who matters and how it all fits. Then you walk straight into the middle of it. Nobody sees the groundwork.' },
    ],
  },
  {
    id: 'a9_swim_end', age: 9, scene: 'pool',
    intro: 'Seven years in the pool. This is the last one.',
    prompt: 'Final gala before you pack swimming in for good.',
    options: [
      { id: 'win', label: 'Win it. Go out on top and never come back.',
        fx: { ATH: 9, HAP: 6 }, xp: 90, count: { wins: 1, swim_years: 7 }, flag: 'swim_champion',
        result: 'You touch the wall first and climb out knowing you will not do this again. Seven years, finished on a win. Your coach is genuinely gutted to lose you.' },
      { id: 'relay', label: 'Swim the relay so the team gets a medal, not you',
        fx: { ATH: 7, CHA: 8, HAP: 5 }, xp: 90, count: { swim_years: 7 }, flag: 'team_first',
        result: 'You give up your individual event to anchor the relay. They win by a body length. Four medals instead of one.' },
      { id: 'mess', label: 'Mess about, do a bomb off the blocks, enjoy the last one',
        fx: { NAU: 8, HAP: 8, ATH: 4 }, xp: 85, count: { trouble: 1, swim_years: 7 },
        result: 'Disqualified from your last ever race for the single greatest bomb in the history of the pool. Half the gallery cheer. You are asked to leave.' },
    ],
  },
  {
    id: 'a9_wwe', age: 9, scene: 'ring',
    intro: 'WWE arrives in your life this year and takes it over completely.',
    prompt: 'It is not just the wrestling. It is the entrances, the promos, the whole thing.',
    options: [
      { id: 'promo', label: 'The promos. You start cutting your own in the mirror.',
        fx: { CHA: 10, MUS: 6, CRE: 6 }, xp: 90, flag: 'wwe_promo', secret: 'mic_skills',
        result: 'You do full promos into a hairbrush. It is genuinely training. Everything you ever do on a mic after this traces back to a bedroom in Hitchin.' },
      { id: 'moves', label: 'The moves. Elowen is about to have a very difficult year.',
        fx: { ATH: 8, NAU: 9, HAP: 6 }, xp: 90, count: { trouble: 3 }, rel: { elowen: -6 }, flag: 'wwe_moves',
        result: 'The sofa becomes the top rope. Elowen takes a People\'s Elbow she did not consent to. Alex bans wrestling in the house four separate times.' },
      { id: 'business', label: 'The business of it — how it is all actually built',
        fx: { BIZ: 9, SMR: 8, CRE: 5 }, xp: 95, flag: 'wwe_kayfabe',
        result: 'You work out that the storyline is the product. Nine years old and you have understood something about entertainment that most adults never do.' },
    ],
  },

  // --------------------------------------------------------------- AGE 10
  {
    id: 'a10_year6', age: 10, scene: 'school_mid',
    intro: 'Year 6. Five people walk into your life in the same term and stay for the rest of it.',
    prompt: 'Jack, Forrest, Ollie C, Ollie (Hen) and Oscar. Where do you plant yourself?',
    options: [
      { id: 'popular', label: 'With Jack and Forrest — straight into the middle of everything',
        fx: { CHA: 10, HAP: 6, SMR: 4 }, xp: 100, flag: 'year6_popular',
        rel: { jack: 18, forrest: 18, ollie_hen: 8, oscar: 8, ollie_c: 8 },
        result: 'Two weeks and you are part of the loudest, funniest, most-watched table in the year. Jack and Forrest bring the room; you bring the ideas.' },
      { id: 'chaos', label: 'With Ollie C — chaos recognises chaos',
        fx: { NAU: 10, CHA: 6, HAP: 6 }, xp: 100, flag: 'year6_chaos',
        rel: { ollie_c: 20, boyd: 8, ollie_b: 8, jack: 8, forrest: 8, oscar: 6, ollie_hen: 6 },
        result: 'You, Boyd, Ollie B and now Ollie C. Four of you. The staff start splitting you up in seating plans, which does not work.' },
      { id: 'all', label: 'All of them — you are not picking a table',
        fx: { CHA: 8, SMR: 7, HAP: 7 }, xp: 110, flag: 'year6_connector',
        rel: { jack: 12, forrest: 12, ollie_c: 12, ollie_hen: 12, oscar: 12, boyd: 8, ollie_b: 8 },
        result: 'You are the one person who moves between every group without it being weird. The naughty lot, the clever lot, the football lot. Ambivert, working as intended.' },
    ],
  },
  {
    id: 'a10_sharks_fold', age: 10, scene: 'pitch',
    intro: 'Shillington Sharks fold. Eight years, gone, because there are not enough players in the age group.',
    prompt: 'Last training session. Coach tells everyone at the end.',
    options: [
      { id: 'save', label: 'Try to save it — go and recruit players yourself',
        fx: { BIZ: 8, CHA: 9, ATH: 4 }, xp: 100, flag: 'tried_to_save_sharks', secret: 'never_folds',
        result: 'You get four names in a week off your own back. It is not enough and it was never going to be, but the coach never forgets that a ten-year-old tried.' },
      { id: 'grief', label: 'Take it badly. Eight years is your whole life.',
        fx: { HAP: -8, SMR: 5, ATH: 3 }, xp: 100, flag: 'sharks_grief',
        result: 'You are quiet the whole way home. It is the first real loss you have had, and it is a football club in a Bedfordshire village, and it matters enormously.' },
      { id: 'next', label: 'Already thinking about where you sign next',
        fx: { SMR: 7, ATH: 6, BIZ: 4 }, xp: 100, flag: 'forward_looking',
        result: 'You are gutted for about four hours. Then you are asking Dad which clubs run trials. Baldock comes up in that conversation for the first time.' },
    ],
  },
  {
    id: 'a10_loft', age: 10, scene: 'loft',
    intro: 'Dad is up in the loft looking for the Christmas box. You are on the ladder holding the torch.',
    prompt: 'The torch swings across the rafters and lands on three foot six of red and blue. Mario. You have not thought about him in four years.',
    options: [
      { id: 'down', label: 'Bring him down. Right now. He is not going back up there.',
        fx: { HAP: 12, CRE: 8 }, xp: 130, flag: 'mario_returns', secret: 'mario_reunion',
        result: 'You carry him down the ladder like he weighs something. He is dusty and squashed on one side and exactly the same. He goes in the corner of your room and this time he stays.' },
      { id: 'sit', label: 'Sit down in the loft with him for a bit first',
        fx: { HAP: 9, SMR: 7, CRE: 6 }, xp: 135, flag: 'mario_returns', secret: 'mario_reunion',
        result: 'Dad finds the Christmas box and turns round and his ten-year-old is sat cross-legged in the insulation with a giant Mario, not saying anything. He leaves him to it.' },
      { id: 'leave', label: 'Leave him. You are ten. That was a different kid.',
        fx: { SMR: 6, HAP: -5 }, xp: 110, flag: 'mario_left',
        result: 'You close the hatch. You think about it on and off for about a week and then you stop. Some part of you always knows he is still up there.' },
    ],
  },

  // --------------------------------------------------------------- AGE 11
  {
    id: 'a11_knights', age: 11, scene: 'pitch',
    intro: 'Baldock Knights. New club, new badge, and the start of something long.',
    prompt: 'Trial day. Forty kids, one pitch, and a lot of parents pretending not to watch.',
    options: [
      { id: 'dominate', label: 'Take over the game completely and let the football talk',
        fx: { ATH: 10, CHA: 5 }, xp: 110, flag: 'knights_signed', count: { goals: 3, knights_years: 1 },
        result: 'Three goals in a forty-minute trial. They offer you a place before you have got your boots off. You sign for Baldock Knights and you are not going anywhere for a long time.' },
      { id: 'leader', label: 'Organise the whole trial team like you have played there for years',
        fx: { CHA: 9, SMR: 7, ATH: 6 }, xp: 110, flag: 'knights_signed', count: { knights_years: 1, assists: 2 },
        result: 'You are shouting shape at eleven other strangers within ten minutes. The coach signs you and pulls your dad aside to say he has not seen that in an eleven-year-old.' },
      { id: 'quiet', label: 'Play your normal game. No showboating. Just be the best one there.',
        fx: { ATH: 9, SMR: 6 }, xp: 115, flag: 'knights_signed', count: { knights_years: 1, goals: 1 }, secret: 'no_fuss',
        result: 'You do not do a single trick. You just do everything right, quickly, all afternoon. The coach\'s note says: "Best player on the pitch. Did not need to tell anyone."' },
    ],
  },
  {
    id: 'a11_arlesey', age: 11, scene: 'pitch',
    intro: 'Arlesey Town come in as well. One season. As it turns out, exactly one season.',
    prompt: 'You can play for both. It is a lot of football. It is a LOT of football.',
    options: [
      { id: 'both', label: 'Both. Knights and Arlesey. Every weekend, all season.',
        fx: { ATH: 11, HLT: -4, HAP: 6 }, xp: 120, flag: 'arlesey_star', count: { goals: 12, knights_years: 0 },
        result: 'Saturday for one, Sunday for the other, from September to May. You are comfortably the best player at Arlesey and you barely drop a level at Baldock. You are also completely knackered by March.' },
      { id: 'arlesey_all', label: 'Go all in at Arlesey — be the best player they have ever had',
        fx: { ATH: 12, CHA: 6 }, xp: 120, flag: 'arlesey_legend', count: { goals: 18 }, secret: 'one_season_legend',
        result: 'Eighteen goals in one season for a club that will not exist in twelve months. Some of those games nobody filmed and nobody wrote down and they still happened.' },
      { id: 'manage', label: 'Manage the load properly so you are flying in May, not dead',
        fx: { ATH: 8, SMR: 9, HLT: 5 }, xp: 125, flag: 'load_managed', count: { goals: 9, knights_years: 0 },
        result: 'Eleven years old and you are already managing your own minutes. By the end of the season you are the only one in either squad who has not picked up a knock.' },
    ],
  },
  {
    id: 'a11_oscar', age: 11, scene: 'school_mid', requires: (s) => (s.relationships.oscar ?? 50) > 50,
    intro: 'It comes out at lunch, completely by accident, in the middle of a conversation about something else.',
    prompt: 'Oscar\'s birthday is your birthday. Same day. Same year. Same hospital. The room next door.',
    options: [
      { id: 'mad', label: 'Lose your minds about it for a solid week',
        fx: { HAP: 10, CHA: 6 }, xp: 120, rel: { oscar: 25 }, flag: 'oscar_twin', secret: 'room_next_door',
        result: 'You get both mums on the phone to confirm it. They were on the same ward on the same night. Eleven years of being two streets apart and nobody mentioned it.' },
      { id: 'joint', label: 'Immediately start planning every birthday as a joint one, forever',
        fx: { CHA: 8, BIZ: 5, HAP: 8 }, xp: 125, rel: { oscar: 22 }, flag: 'joint_birthdays', secret: 'room_next_door',
        result: 'A joint party every year from here on. It gets bigger every time. By eighteen it is a genuine event and people ask about it months in advance.' },
      { id: 'cool', label: 'Play it completely cool and file it away as the best fact you own',
        fx: { SMR: 6, CHA: 6, HAP: 6 }, xp: 120, rel: { oscar: 16 }, flag: 'oscar_twin', secret: 'room_next_door',
        result: 'You shrug at the time. You then tell literally every single person you meet for the rest of your life.' },
    ],
  },

  // --------------------------------------------------------------- AGE 12
  {
    id: 'a12_arlesey_fold', age: 12, scene: 'pitch',
    intro: 'Arlesey Town folds. One season, and it is gone.',
    prompt: 'Two clubs folding under you in three years. That is a pattern you have noticed.',
    options: [
      { id: 'build', label: 'Decide that one day you will run one that does not fold',
        fx: { BIZ: 12, CHA: 6, SMR: 6 }, xp: 130, flag: 'will_build_a_club', secret: 'the_promise',
        result: 'Not a daydream. A decision, made at twelve, in a car park, in the rain. You are going to build something that lasts. You do not tell anyone for years.' },
      { id: 'knights', label: 'Pour everything into Baldock instead',
        fx: { ATH: 10, CHA: 6 }, xp: 125, count: { knights_years: 1, goals: 8 }, flag: 'knights_committed',
        result: 'One club now, and all of it. You go from good at Baldock to untouchable at Baldock in about four months.' },
      { id: 'shrug', label: 'Shrug. Clubs fold. You do not.',
        fx: { SMR: 7, HAP: 5, ATH: 5 }, xp: 125, count: { knights_years: 1 }, flag: 'unshakeable',
        result: 'Sharks, Arlesey, gone. You are still here and still the best one on the pitch. It stops being sad and starts being a fact about the world.' },
    ],
  },
  {
    id: 'a12_money', age: 12, scene: 'bedroom',
    intro: 'The Scratch stuff, the sweets, the car washing. It has all been practice.',
    prompt: 'You want a real one. Something that runs without you standing there.',
    options: [
      { id: 'reselling', label: 'Buy and resell — trainers, cards, whatever is moving',
        fx: { BIZ: 13, SMR: 7, NAU: 4 }, xp: 135, money: 140, count: { ventures: 1, deals: 5 }, flag: 'reseller',
        result: 'You work out what things are worth before other people do. £140 profit in a term, kept in a shoebox, tracked in a notebook that is weirdly well organised.' },
      { id: 'content', label: 'Make stuff — music, clips, edits — and build an audience first',
        fx: { CRE: 12, MUS: 9, CHA: 6 }, xp: 135, count: { ventures: 1, gigs: 2 }, flag: 'building_audience', fame: 3,
        result: 'No money yet. A few hundred people who care, though. You have understood the correct order of operations, which almost nobody does at twelve.' },
      { id: 'service', label: 'Sell what you can already do — build websites and games for people',
        fx: { BIZ: 10, COD: 11 }, xp: 140, money: 210, count: { ventures: 1, scratch_projects: 2 }, flag: 'freelancing',
        result: 'Two local businesses and somebody\'s uncle. £210. You have invoices. Actual invoices, at twelve, made in a word processor with a logo you designed yourself.' },
    ],
  },
  {
    id: 'a12_crew', age: 12, scene: 'town',
    prompt: 'Boyd, Ollie B and Ollie C have found a building site with no fence on the far side.',
    options: [
      { id: 'go', label: 'Go. Obviously go.', fx: { NAU: 10, ATH: 7, HAP: 7 }, xp: 130,
        count: { trouble: 2 }, rel: { boyd: 10, ollie_b: 8, ollie_c: 10 }, flag: 'site_night',
        result: 'Two hours on scaffolding you should absolutely not be on. A security light, a genuine sprint, and a story the four of you still tell in your forties.' },
      { id: 'plan', label: 'Go, but be the one who works out the way back out first',
        fx: { NAU: 7, SMR: 9, CHA: 5 }, xp: 140, rel: { boyd: 12, ollie_b: 10, ollie_c: 12 }, flag: 'the_brains', secret: 'always_an_exit',
        result: 'You find the gap in the hoarding before you go in. When the light comes on, all four of you are through it in eleven seconds. Boyd calls you a genius. He is not wrong.' },
      { id: 'divert', label: 'Talk them into something just as good and far less arrestable',
        fx: { CHA: 10, SMR: 7, NAU: 4 }, xp: 135, rel: { boyd: 8, ollie_b: 6, ollie_c: 6 }, flag: 'the_steadier',
        result: 'You redirect three genuinely reckless twelve-year-olds into an all-night football tournament under the car park lights. Same buzz, no police.' },
    ],
  },
];
